### PR TITLE
poke compliance api

### LINKED ISSUE #125: Trigger a compliance API check when you app deploys
The intent is to trigger a compliance API check whenever you app has deployed and ready. Because this is a non-deterministic event, the requirement is for the app to decide when the best point in time for that is.

The compliance watcher application exposes an internal kubernetes endpoint (https://github.com/cds-snc/report-a-cybercrime/blob/master/compliance/watcher-deployment.yaml#L34), which can be triggered by a POST request.

In other words, you need to make a POST request to:

`compliance-watcher.symmorfosi.svc.cluster.local:3000/run_compliance`

to trigger a compliance run. I would recommend putting it in here or thereabouts:

https://github.com/cds-snc/report-a-cybercrime/blob/master/frontend/src/index.js#L22

### PR DESCRIPTION
**Pull request by sastels**
resolves #125

### CODE REVIEW

**Comment by sastels** [comment]
@maxneuvians is this what you had in mind?

**Comment by maxneuvians** [comment]
Agreed - I am not happy about this, it was just the most simplest thing I could come up with. The idea is that it is a fire and forget hook, so if it fails locally, who cares (clearly too much elixir speaking). 

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook look like a good alternative approach. Hopefully can

**Comment by maxneuvians** [comment]
Another option is to throw the trigger logic in an init container, does not concern the app logic at all, but it would no ensure that the app is up when the checks are run

**Comment by maxneuvians** [comment]
To overcome the problem of using an init container and the main container not being ready when the checks run, the watcher app could receive a delay param that says, wait X seconds before running the check, because the main container should be up by then. Again if after X seconds the thing is not up, you have a problem. There is this https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/ but the hooks are no `Container is running` hooks

**Comment by maxneuvians** [comment]
I will take a look at this here: https://stackoverflow.com/questions/35192712/kubernetes-watch-pod-events-with-api, to see if I can tap into a `Running` event

**Comment by maxneuvians** [comment]
Maybe add a try/catch around it until I have a chance to review the other implementations.

**Comment by sastels** [comment]
locally, with the catch, I get the following sent to the logs (as expected)
```
{ cloudEventsVersion: '0.2',
  contentType: 'text/plain',
  data:
   'Error triggering compliance api: FetchError: request to http://compliance-watcher.symmorfosi.svc.cluster.local:3000/run_compliance failed, reason: getaddrinfo ENOTFOUND compliance-watcher.symmorfosi.svc.cluster.local compliance-watcher.symmorfosi.svc.cluster.local:3000',
  eventID: '3f6e8aa1-d5cf-4605-b540-ffa48d2a8cc4',
  eventTime: '2019-02-15T19:45:47.044Z',
  eventType: 'com.github.cds-snc.error',
  eventTypeVersion: '1.0',
  source: '/' }
```

**Pull request merged**
