### PR TITLE
Update Suspect Clues Form

### LINKED ISSUE #2156: Update Suspect Clues Form
Update SuspectCluesForm.js to use Formik, Yup, and Bootstrap as documented in issue #2136. These changes have been made to HowDidItStartForm.js, you can them here - #2138.  

Textarea components have already been created. This one should be pretty straight forward.

### PR DESCRIPTION
**Pull request by kevinyang06**
Fixes #2156

# Description

> Update SuspectCluesForm.js to use Formik, Yup, and Bootstrap as documented in issue #2136. These changes have been made to HowDidItStartForm.js, you can them here - #2138.
# Any new packages installed?

> Give details

# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

**Comment by ying-chen-cds** [comment]
The following code should not be removed
       {false ? ( // the following trans tags are for analyst email
        <div>
          <Trans id="suspectClues.suspectDetails" />
        </div>
      ) : null}

**Comment by ying-chen-cds** [comment]
The following code should not be removed
```
     {false ? ( // the following trans tags are for analyst email
        <div>
          <Trans id="suspectClues.suspectDetails" />
        </div>
      ) : null} 
```

**Comment by ying-chen-cds** [comment]
The ids of the following codes are wrong
```
    submit={<Trans id="howDidItStartPage.nextButton" />}
    label={<Trans id="howDidItStartPage.nextPage" />}
```

**Comment by ying-chen-cds** [comment]
The original width of the textArea is bigger and aligned with the helper text, and looks better. Can we increase the width of textArea to its original size?

**Comment by ying-chen-cds** [comment]
I don't think we need validation for this form

**Comment by kevinyang06** [comment]
> The following code should not be removed
> 
> ```
>      {false ? ( // the following trans tags are for analyst email
>         <div>
>           <Trans id="suspectClues.suspectDetails" />
>         </div>
>       ) : null} 
> ```

fixed

**Review by sdzhangtao — APPROVED** [review]

**Pull request merged**
