### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by sastels**
upgraded a bunch of packages in `frontend`. Remaining is `jest` and `babel-jest`, which have major upgrades that broke things.

### CODE REVIEW

**Comment by maxneuvians** [comment]
Interesting bundle size only increased by 1 byte

**Comment by sastels** [comment]
bundle now 200B bigger

**Comment by maxneuvians** [comment]
Byte math seems to be off, probably rounding error

**Comment by evadb** [comment]
Can we upgrade React too in this one? :o

**Comment by sastels** [comment]
@evadb AFAIK react was already upgraded at some point? (Latest is 16.8.1 as is in the lock file)
https://github.com/cds-snc/report-a-cybercrime/blob/upgrade_packages/frontend/package-lock.json#L3440

**Pull request merged**
