### PR TITLE
P1 - Remove 'Report another scam' button

### PR DESCRIPTION
**Pull request by anikbrazeau**
Usability testing revealed users do not want to signal another fraud

### CODE REVIEW

**Comment by anikbrazeau** [comment]
[Making changes to content for P1](https://trello.com/c/wy8tKYrW/448-making-changes-to-content-for-p1)

**Comment by anikbrazeau** [comment]
[Style buttons that perform different functions differently from each other (more details in card).](https://trello.com/c/R57W7XY9/68-style-buttons-that-perform-different-functions-differently-from-each-other-more-details-in-card)

**Comment by anikbrazeau** [comment]
[Style buttons that perform different functions differently from each other (more details in card).](https://trello.com/c/R57W7XY9/68-style-buttons-that-perform-different-functions-differently-from-each-other-more-details-in-card)

**Comment by melbanyard** [comment]
> Usability testing revealed users do not want to signal another fraud

Hiya @anikbrazeau while yes, usability testing did not indicate it was a need, it should still be something that we include. What I think is most important, is that right now, the way that it is styled, indicates that it is the next step. Include "report another fraud" but don't style it the way the "start button" or "submit button" was

**Comment by anikbrazeau** [comment]
We can add it as a link back to the start in bullets and to the NC3 page also.

**Comment by anikbrazeau** [comment]
See #615

**Pull request closed without merging**
