### PR TITLE
Change date format on 'Money'and 'How did it start' pages

### LINKED ISSUE #1231: New date input field format
## Summary

How might we reduce the risk of the date entered being wrong?
-- autocomplete?
-- break into smaller components?
-- date picker / calendar

### LINKED ISSUE #1348: Change date format on 'How did it start' and 'Money' pages
Link to #1231 

## Summary

Making the date entry more exact and precise to map more easily to the FRS.

## Design Detail

Screen Shot 2020-02-11 at 2 46 59 PM

Screen Shot 2020-02-11 at 2 46 53 PM

Screen Shot 2020-02-11 at 2 47 07 PM

Screen Shot 2020-02-11 at 2 47 12 PM

### LINKED ISSUE #1429: Add links to Information Page tips
## Summary

Add links to Equifax and TransUnion on Information page

                      <A
                        href={
                          i18n.locale === 'en'
                            ? 'https://www.consumer.equifax.ca/personal/'
                            : 'https://www.consumer.equifax.ca/personnel/'
                        }
                        isExternal // Opens new tab
                      />
                      <A
                        href={
                          i18n.locale === 'en'
                            ? 'https://www.transunion.ca/'
                            : 'https://www.transunion.ca/fr'
                        }
                        isExternal // Opens new tab
                      />

** I've tried adding <0></0> and <1></1> in the lingui files but this takes out all spacing around the links.

## Design Detail

Screen Shot 2020-02-18 at 5 22 48 PM

### PR DESCRIPTION
**Pull request by naomiseminega**
Fixes #1348
Fixes #1231 

# Description
- Added new date format, to show date in 3 parts, making the date entry more exact and precise to map more easily to the FRS.

# Any new packages installed?
No
# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work
None

### CODE REVIEW

**Comment by anikbrazeau** [comment]
Seems that the dates don't appear on confirmation page when entered in the form fields.

**Comment by naomiseminega** [comment]
> @naomiseminega it seems that the dates don't appear on the confirmation page when entered in the form fields?

@anikbrazeau I haven't merge this PR yet (still solving conflicts), but I made sure that the dates for both pages appear on the confirmation page.

**Comment by amazingphilippe** [comment]
@naomiseminega Can we take a look at restricting the content that can be entered in the fields. Maybe limiting to 2 digits for month and day, and to 4 digits for the year
Screen Shot 2020-02-19 at 11 32 21 AM

**Comment by naomiseminega** [comment]
> @naomiseminega Can we take a look at restricting the content that can be entered in the fields. Maybe limiting to 2 digits for month and day, and to 4 digits for the year
> Screen Shot 2020-02-19 at 11 32 21 AM

@amazingphilippe Yes for sure!  Probably won't be done by today though. Github is down/ slow on my end and I'm still trying to solve conflicts and merge hopefully before this afternoon.

**Comment by anikbrazeau** [comment]
Fixes #1348

**Pull request merged**
