### PR TITLE
Added a TOTP code to bypass submission per day restriction

### LINKED ISSUE #1882: Add the ability to get react app when daily counter is full
## Summary

> If we have reached the number of reports for the day, the system will not serve you the react app and it will redirect you to CAFC.  See code here: https://github.com/cds-snc/report-a-cybercrime/blob/f0ee9351aa95d45491a61637f06001c25b8c1761/f2/src/utils/saveRecord.js#L47

> However, if we launch a new release or hotfix we need to submit some test reports / smoke tests.  We need a way to pass a token or some way to override the counter.

## Design detail

> We are _always_ able to post to /submit so that isn't an issue.

### PR DESCRIPTION
**Pull request by ngosset**
Fixed #1882

This PR adds a TOTP (Google Authenticator, Authy, Microsoft Authenticator, etc) code as a "bypass" to allow us to access the app even when we hit the report limit for the day.

This could be used for devs to test the app even when we are closed for the day.

Instructions to test:

1.  Generate a secret using the generatesecret.js node app. This is a stand-alone script with it's own packages. So you will need to 'npm i' separate from the app.

```
cd /utils/totp
npm i
node generatesecret.js

```
This will create two files. 
'secret' is a text file with the TOTP secret. 
'code.html' is a HTML file with a QR code of the secret

2. Copy the contents of /utils/totp/secret file and put it in your .env file:
Example:
TOTP_SECRET=OBKVGJLUHFEXQZZDMFVTWQTDFI2D4N3QEMSEM2ZRMRXGOWSUOVRA

3. Using an authenticator app of your choice, open the code.html file and scan the QR code.

4. Set your "SUBMISSIONS_PER_DAY" value very low in the .env (1)

5. Build and run the app. Don't forget to also "npm i" on the app to install new library (speakeasy)

6. Fill out some test reports. You need to submit more reports than your "SUBMISSIONS_PER_DAY" value. Once this is done, try to access the app and verify it redirects you to CAFC website

7. Once you cannot access your local app without being redirected, try the TOTP code to verify the bypass. Copy the 6 digit TOTP code from your authenticator and pass it to the app in the URL as a query parameter
Example:
http://localhost:3000/?totp=123456

Outstanding questions:
Right now the app works as normal once loaded. We could add code to let analysts know it's a test report and they can ignore it.

### CODE REVIEW

**Comment by ngosset** [comment]
> This pull request **introduces 1 alert** when merging [61ad2dd](https://github.com/cds-snc/report-a-cybercrime/commit/61ad2dd1567b420ef6c50e927511aa74a3ec2c4b) into [22c956e](https://github.com/cds-snc/report-a-cybercrime/commit/22c956efe1ce88b5100fc0c17d4626f7066e39db) - [view on LGTM.com](https://lgtm.com/projects/g/cds-snc/report-a-cybercrime/rev/pr-f73e8c9a30f655a9a89fcf6941900555653f3110)
> 
> **new alerts:**
> 
> * 1 for Missing rate limiting

Not sure I need to fix this? It isn't really authentication. Worst case if someone brute forced the TOTP we get some dummy reports? They can submit to /submit anyway without the react app so the TOTP isn't really protecting anything...

**Comment by davidheerema** [comment]
@lmcbhvu I am testing this PR locally and I find a situation where my browser is telling me there was an error with the report but It seems to be successful?

Here is the server logging (there is no evidence of an error being logged):

> Availability configured
Self harm word list: aspenite
Warning: CosmosDB not configured. Data will not be saved to CosmosDB database. Please set the environment variables COSMOSDB_NAME and COSMOSDB_KEY
ERROR: Notify environment variable NOTIFY_ENGLISH_CONFIRMATION_TEMPLATE_ID is missing. Emailing links will probably not work.
ERROR: Notify environment variable NOTIFY_FRENCH_CONFIRMATION_TEMPLATE_ID is missing. Emailing links will probably not work.
Notify client created
Listening at port 3000
ldapQuery: Certificate for david.heerema@rcmp-grc.gc.ca (000111621) found
{ availableData:
   { numberOfSubmissions: 0,
     numberOfRequests: 0,
     lastRequested: undefined } }
LDAP certs successfully fetched for: david.heerema@rcmp-grc.gc.ca
Referrer:undefined
New Request. {"numberOfRequests":0}
Encrypted Mail: Message encrypted
Encrypted Mail: Message sent to david.heerema@rcmp-grc.gc.ca: <b2ad21b3-d357-4db5-972f-9e23f2870f27@racc.m.notification.alpha.canada.ca>

You can see that I am specifying my email and HRMIS in the .env so I _am_ getting the report emails to my outlook.

I am _not_ however specifying the database connection information.

Here are some values from my .env:

```
# database for reports
#COSMOSDB_NAME=mpsccdscybercrimecosdb
#COSMOSDB_KEY=ddd

# Blob Storage for files
BLOB_STORAGE_NAME=rcmpblobstorage
BLOB_STORAGE_KEY={removed valid key}

# self harm words
SELF_HARM_WORDS=aspenite

# file scanning
CLAM_URL=mpdcdscybercrimeclamavdevci.canadacentral.azurecontainer.io
CONTENT_MODERATOR_SERVICE_KEY={removed valid key}

# encrypting email to intake analyst
LDAP_URL=ldap://pki-dsa.rcmp-grc.gc.ca:389
LDAP_UID=000111621

# sending encrypted emails
MAIL_HOST=email-smtp.us-east-1.amazonaws.com
MAIL_USER={removed}
MAIL_PASS={removed}
MAIL_FROM=NCFRS <ncfrs@racc.m.notification.alpha.canada.ca>

# Notify configuration
NOTIFY_API_BASE_URL=https://api.notification.alpha.canada.ca
NOTIFY_API_KEY={removed valid key}
NOTIFY_CONFIRMATION_TEMPLATE_ID={removed}
NOTIFY_FEEDBACK_TEMPLATE_ID={removed}
FEEDBACK_EMAIL=david.heerema@cds-snc.ca

# Google Analytics
GOOGLE_ANALYTICS_ID={removed}

# rate limiting
SUBMISSIONS_PER_DAY=2
SECONDS_BETWEEN_REQUESTS=10

TOTP_SECRET={removed}
```
Can you reproduce?

Screen Shot 2020-05-13 at 11 16 25 AM

**Comment by khalidelaggan** [comment]
Working on this now with hong

**Comment by khalidelaggan** [comment]
@davidheerema  Was this locally running `npm run build` followed by`npm run prod`?

**Comment by davidheerema** [comment]
nmp run prod (that does a build).

update: Hong and khalid were able to replicate the situation.

**Comment by ngosset** [comment]
Hey guys, if you were testing this - re-pull the branch. There was a bug in our code (before this PR) where we were setting numberOfSubmissions to undefined by setting it to the value of a function that didn't return anything. See commit to fix it here: https://github.com/cds-snc/report-a-cybercrime/pull/1911/commits/1ba1804d8742f349442cc3c0506476d2fa09b93a

**Comment by khalidelaggan** [comment]
My apology for the delay on this, it's still in my todo and hoping to help review it by Monday with Hong

**Pull request merged**
