### PR TITLE
Use keyvault

### LINKED ISSUE #1189: use Azure Keyvault
## Summary

We need to store our app secrets in Keyvault rather than just putting them in App Service

## Motivation

Best practices, as well as an RCMP requirement.

## Drawbacks

Code around secrets becomes more complicated, and there are more pieces to maintain.

## Unresolved questions

None.

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1189 

# Description

Hook up app to Azure Key Vault and get the CosmosDB name and Key from it.

# Any new packages installed?

- @azure/identity: generate Azure credentials
- @azure/keyvault-secrets: connect to Key Vault

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work

- Need to change the script to get the AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and AZURE_TENANT_ID and add to App Service env vars
- undoubtedly need to improve the permissions of the service principal. For one thing, probably just needs to be read-only.
- `server.js` is getting pretty big. Should refactor it and extract some functions to their own files.

### CODE REVIEW

**Comment by davidheerema** [comment]
Hey Steve,

I am going to want to tweak the CLI and likely the Service
principle creation - maybe associating the SP to a resource restriction or
vnet integration if possible.

I see that you specify additional environment variables that you don't use
in code:
# need to get the AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and AZURE_TENANT_ID
and add to App Service env vars
I think that there may be a better way to integrate the sp credentials into
the app service but I have to refresh my memory.

Do you need this PR merged immediately or can we wait for me to check some
things out and talk about it a bit further?

Did you test the CLI to make sure the resources are created successfully
using those commands?

**Comment by sastels** [comment]
> Do you need this PR merged immediately or can we wait for me to check some things out and talk about it a bit further? 

it can wait. Though we can also just ship it as is and change it later. I'm good either way.

> Did you test the CLI to make sure the resources are created successfully using those commands?

These are the commands I used to set up Keyvault on CDS' app, they might require changes for the RCMP system :)

**Comment by davidheerema** [comment]
https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

There may be a way that we can integrate keyvault seemlessly to the code - however we have to first determine the value in using keyvault for these secrets

**Comment by sastels** [comment]
I think if we want to use Keyvault, ☝️ is the way to go. Closing this PR for now, but if we decide to put Keyvault in the code (vs just in App Service) we can always come back and see what's done here.

**Pull request closed without merging**
