### PR TITLE
Send encrypted email to intake analyst

### PR DESCRIPTION
**Pull request by sastels**
# Description

- look up cert for intake analyst
- encrypt json into attachment
- email attachment

# Any new packages installed?

- child_process: run openssl on the command line
- ldapjs: connect to ldap server to get cert
- nodemailer: connect to smtp server and send email

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work

probably could use some cleanup. Also, figure out some automated tests

### CODE REVIEW

**Comment by davidheerema** [comment]
1) Do we need to include a hardcopy of the certificate in the repo?
2) Does this PR have unrelated changes to some pages in f2 like
confirmation page?

I'm getting used to this and learning.

**Comment by sastels** [comment]
> 1) Do we need to include a hardcopy of the certificate in the repo? 

I think we can just use the ldap lookup as we have here, with the analyst's uid as an environment variable in App Service

> 2) Does this PR have unrelated changes to some pages in f2 like confirmation page? I'm getting used to this and learning.

I don't think so - this emailing should happen without the victim even knowing about it - ie, essentially, the victim doesn't need to know the details of how their report gets submitted to the RCMP.

**Comment by davidheerema** [comment]
1. Steve, if you look at the files changed in this PR you'll see there's a
cert you checked in... I will drop this file from the PR.

2. There was also some formatting cleanup on some of the react pages
unrelated to your change.  I'm guessing it was some automation that checked
these changes into your PR.  Norm went through with me and look like
they're good to go as well.  I just couldn't follow initially why they may
have been related to this PR for email.

**Comment by sastels** [comment]
> 1. Steve, if you look at the files changed in this PR you'll see there's a cert you checked in... I will drop this file from the PR. 

oh crud - good catch! 

> 2. There was also some formatting cleanup on some of the react pages unrelated to your change. I'm guessing it was some automation that checked these changes into your PR. Norm went through with me and look like they're good to go as well. I just couldn't follow initially why they may have been related to this PR for email.

yeah, I should have commented on that. As you mention I think it was prettier going through and fixing some formatting changes.

**Pull request merged**
