### PR TITLE
Revert Full Report Button

### PR DESCRIPTION
**Pull request by justinr86**
During development of the FYI forms the button to begin a full report was updated. This update broke a test script and all subsequent PRs have failed test cases now. To resolve this, the message property for that button is being reverted. 

Note: French translation come from the failed test result.

### CODE REVIEW

**Comment by justinr86** [comment]
This test is still failing even with the new button text. These must be another reason this test is failing.

**Comment by DianeLiu2019** [comment]
I clicked  "update branch" ,then  the cypress test passed, right now, we have problem with the ContactInfoForm.test.js . Ying is working on it .

**Comment by DianeLiu2019** [comment]
> This test is still failing even with the new button text. These must be another reason this test is failing.

I clicked "update branch" ,then the cypress test passed. right now, we have problem with the ContactInfoForm.test.js . Ying is working on it .

**Comment by DianeLiu2019** [comment]
@lmcbhvu  Hong, I checked the cypress code, you already updated the label  to " Start report", and already merged into master, is that right?

**Comment by lmcbhvu** [comment]
The cypress code in master is the latest code.

**Comment by justinr86** [comment]
This fix has been implemented as part of another PR.

**Pull request closed without merging**
