### PR TITLE
Update most frontend dependencies.

### PR DESCRIPTION
**Pull request by sleepycat**
This commit omits Apollo related things which will follow with some associated
changes in another commit.

Minor change to a test file since Jest now warns about using async with a
describe block.

### CODE REVIEW

**Comment by sastels** [comment]
This is helpful:
New styled system
- Adds long-form props for margin and padding (e.g. marginTop). Shorthand aliases still work as before.

**Comment by keithiancolbourne** [comment]
Just curious...do you decide to update these deps based on a security vulnerability scan or what triggers an update like this?

**Comment by sastels** [comment]
Not sure what tickled Mike this time, but on the VAC project we got in the habit of someone doing it every sprint. Basically, update everything that’s easy, and if there are updates that would break the app, make an issue for them instead.

**Comment by sleepycat** [comment]
Big across-the-board updates like this are usually a "it's been a while" moment. Security driven updates are usually smaller and more focused.

**Pull request merged**
