### PR TITLE
Allow cross-origin requests from antifraudcentre

### PR DESCRIPTION
**Pull request by ngosset**
Allow cross-origin requests if origin is antifraudcentre site

# Any new packages installed?
Nope

# Checklist:

- [X] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [] I have added and needed tests for my changes (in particular for new screens)
- [X] I have added a comment to any confusing code

# Required followup work

Need to test it with CAFC.

### CODE REVIEW

**Comment by ngosset** [comment]
Alternatively should we just allow '*'?

**Comment by timarney** [comment]
Would suggest using https://github.com/helmetjs/helmet 

It's proven / hardened middleware

Also more robust i.e.
- frame guarding, cache control, xss protection, and anti-mime sniffing.

**Comment by ngosset** [comment]
Thanks Tim, I will look into it. Would like do something more robust than what we're doing now.

**Comment by obrien-j** [comment]
@sastels For stuff like this, where it's crossing into 'security' territory, feel free to throw a 'security' label on it, and/or tag @damcom333 for a review. 

Probably a good practice to document @ngosset in your sa&a and continuous delivery practices, as it'll give security folks a warm and fuzzy (or strike fear into their hearts), that the team is conciously looking for opportunities to get security/privacy review on critical pieces of code.

kthxbai 🍰

**Pull request merged**
