### PR TITLE
Logged more detailed error message if content moderator has a problem

### LINKED ISSUE #1885: Don't pass non-images to Content Moderator for scanning
## Summary

The server logs an ERROR when we pass .rtf or .pdf attachments to the content moderator for scanning.  That service is only able to scan bmp, png, jpeg, and gif.

See https://canadacentral.dev.cognitive.microsoft.com/docs/services/57cf753a3f9b070c105bd2c1/operations/57cf753a3f9b070868a1f66c/console

This should not be an error and it makes alarms trigger.

## Steps to reproduce

> Upload a supported file type other than those four and check the console log for the error.

## Possible Solution:

If the attachment is not bmp, png, jpeg, or gif content type (who cares about the file extension) then do not scan the that file.

### LINKED ISSUE #1887: Provide Detailed Content Moderator Errors
## Summary

When their is an issue with content moderator the server Logs the following with no detail:
`Error	" Error in Content Moderator: Error "`

In order to troubleshoot we require the details of the content moderator error.

## Steps to reproduce

> Submit a non-image for scanning, or submit an image of zero size.

### PR DESCRIPTION
**Pull request by sdzhangtao**
Fixes #1887
Fixes #1885 

# Description
Content moderator just logged Error without detailed error message.
> Please include a summary of the change.
Just use JSON.stringify to transform the whole response err object into JSON
# Any new packages installed?
No
> Give details

# Required followup work
No
> Is there anything related to this that still needs to be done (ex: documentation changes).
No
# Checklist:

- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

**Comment by davidheerema** [comment]
I will try test this locally and how the errors now get displayed.

**Comment by davidheerema** [comment]
Here is the testing I did @sdzhangtao.  Please review and let me know if these are the results you expect / are happy with.  I think I am not a very efficient tester like Hong @lmcbhvu :

_I am interested to see how these errors display in the Log Analytics database record, but we will examine that once it is deployed to Master on Azure._

### Test1:

I submit a report with the attached .pdf 
[OUTLINE_7062518512_S001_AA_9583333_117.pdf](https://github.com/cds-snc/report-a-cybercrime/files/4558905/OUTLINE_7062518512_S001_AA_9583333_117.pdf)

**Master branch results:**
`Error in Content Moderator: Error `

**content-moderator-error-logging branch results:**
`Error in Content Moderator: {"statusCode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://canadacentral.api.cognitive.microsoft.com//contentmoderator/moderate/v1.0/ProcessImage/Evaluate","method":"POST","headers":{"Content-Type":"`**image/gif**`","Ocp-Apim-Subscription-Key":"REMOVEDBYDAVE","X-BingApis-SDK-Client":"node-SDK","user-agent":"Node/v11.9.0 (x64-Darwin-19.4.0) ms-rest/2.5.4 azure-cognitiveservices-contentmoderator/4.1.1 Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"Message\":\"Image Size Error\",\"TrackingId\":\"CAC_ibiza_8ebf9fdc-515d-44ab-9b05-3ffd318ae410_ContentModerator.S0_068609a4-98ad-49e5-9d10-bf75aff7ef4e\",\"Errors\":[{\"Title\":\"`**Image Size Error**`\",\"Message\":\"`**Image size is not in allowed range**`.\"}]}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"237","content-type":"application/json; charset=utf-8","expires":"-1","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","apim-request-id":"bb23bf92-f235-4de9-878e-7ff8844997d5","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-content-type-options":"nosniff","date":"Thu, 30 Apr 2020 14:20:59 GMT","connection":"close"},"statusCode":400},"body":{}}`

I am surprised to learn that the error is claiming that it is related to the image size, considering it is not an image at all!  We are setting the Content-Type as image/gif in the request?

### Test2:

I submit a report with a zero-sized .png

**Master branch results:**
`Error in Content Moderator: Error `

**content-moderator-error-logging branch results:**
`Error in Content Moderator: {"statusCode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://canadacentral.api.cognitive.microsoft.com//contentmoderator/moderate/v1.0/ProcessImage/Evaluate","method":"POST","headers":{"Content-Type":"image/gif","Ocp-Apim-Subscription-Key":"8c2f434b31fe4d7eb7533d4e553e7e5c","X-BingApis-SDK-Client":"node-SDK","user-agent":"Node/v11.9.0 (x64-Darwin-19.4.0) ms-rest/2.5.4 azure-cognitiveservices-contentmoderator/4.1.1 Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"Message\":\"Image Size Error\",\"TrackingId\":\"CAC_ibiza_8ebf9fdc-515d-44ab-9b05-3ffd318ae410_ContentModerator.S0_184a27d9-25bc-4004-b0b4-6dff5ab994c7\",\"Errors\":[{\"Title\":\"Image Size Error\",\"Message\":\"Image size is not in allowed range.\"}]}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"237","content-type":"application/json; charset=utf-8","expires":"-1","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","apim-request-id":"83d2d720-efed-4b17-ba46-feaf01ffcf3c","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-content-type-options":"nosniff","date":"Thu, 30 Apr 2020 14:48:12 GMT","connection":"close"},"statusCode":400},"body":{}}`

### Test3:

I submit a report with a zero-sized .png HOWEVER I have configured an invalid value for the content-moderator key with `CONTENT_MODERATOR_SERVICE_KEY=wrongkey`

**Master branch results:**
`Error in Content Moderator: Error: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.`

**content-moderator-error-logging branch results:**
`Error in Content Moderator: {"statusCode":401,"request":{"rawResponse":false,"queryString":{},"url":"https://canadacentral.api.cognitive.microsoft.com//contentmoderator/moderate/v1.0/ProcessImage/Evaluate","method":"POST","headers":{"Content-Type":"image/gif","Ocp-Apim-Subscription-Key":"wrongkey","X-BingApis-SDK-Client":"node-SDK","user-agent":"Node/v11.9.0 (x64-Darwin-19.4.0) ms-rest/2.5.4 azure-cognitiveservices-contentmoderator/4.1.1 Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"error\":{\"code\":\"401\",\"message\":\"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.\"}}","headers":{"content-length":"224","date":"Thu, 30 Apr 2020 14:43:39 GMT","connection":"close"},"statusCode":401},"code":"401","body":{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}}`

### Test4:

I submit a report with a 2.2MB sized file with .png extension which is NOT a valid .png image.
Cisco_WebEx_Add-On

**The error declares there is a problem with the image size... it's not an image!**  Isn't this odd?

**Master branch results:**
`Error in Content Moderator: Error`

**content-moderator-error-logging branch results:**
`Error in Content Moderator: {"statusCode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://canadacentral.api.cognitive.microsoft.com//contentmoderator/moderate/v1.0/ProcessImage/Evaluate","method":"POST","headers":{"Content-Type":"image/gif","Ocp-Apim-Subscription-Key":"REMOVEDBYDAVE","X-BingApis-SDK-Client":"node-SDK","user-agent":"Node/v11.9.0 (x64-Darwin-19.4.0) ms-rest/2.5.4 azure-cognitiveservices-contentmoderator/4.1.1 Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"Message\":\"Image Size Error\",\"TrackingId\":\"CAC_ibiza_8ebf9fdc-515d-44ab-9b05-3ffd318ae410_ContentModerator.S0_e18a8916-daba-4b84-8c0d-22eeaa2f0100\",\"Errors\":[{\"Title\":\"Image Size Error\",\"Message\":\"Image size is not in allowed range.\"}]}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"237","content-type":"application/json; charset=utf-8","expires":"-1","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","apim-request-id":"d0589f30-b981-4947-95a8-0f8c4a1fe0f8","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-content-type-options":"nosniff","date":"Thu, 30 Apr 2020 14:57:50 GMT","connection":"close"},"statusCode":400},"body":{}} `

**Comment by sastels** [comment]
Sweet! my only question: do we want to leave the whole json blob there in the logging, or do we want to just report part of it? It might be good to only report part (say the error title) if it's an error we're familiar with (ie the size error) and the whole blob otherwise?

My thinking is that size errors aren't really "errors" in our app, but things like CM being misconfigured or something might be. Thoughts? Not that these logs are just for us, so what's best for the devs / operators?

**Comment by davidheerema** [comment]
> do we want to leave the whole json blob there in the logging, or do we want to just report part of it? 

I was thinking that printing the Error title and Message would be good.  Keeping in mind I believe that there could be more than one Error returned in the response so we have to loop through?

> My thinking is that size errors aren't really "errors" in our app, but things like CM being misconfigured or something might be.

If CM is misconfigured that's an error.  If the content moderator had an error scanning a supported file type, I would say that's an error.  If we cannot connect to content moderator, I'd say error as well.  We are cleaning all this up slowly!

**Comment by sdzhangtao** [comment]
Good testing, Dave!!!
I surely can parse into the json object to get what need. The message and title etc.
I found that the json object that Azure cognitive services returning are changing sometimes without notices. They don't have a strong schema like an API interface does. Logging the whole json object does conform to one lesson I learned along the years. The tolerant reader. It means we don't rely on its schema too much.
Also in exceptional situations, it's typically better to have more information than less information. But I am open to suggestions.

If you guys look at the 2nd change in this PR, that error is actually an exception, so I choose to log its stacktrace. A old habbit from Java. I am dying for stacktrace during debugging a problem.

I think we need to generalize this logging solution shortly. Using Winston or something.

**Comment by davidheerema** [comment]
I am ok with keeping the whole response for now then.

However I do not like how the response is saying that our size is too small when we submit a pdf which would theoretically be a correct size.  Are we crafting our submits wrong with the gif content type?  I want cog services to tell me "hey, we don't scan that type - stop it!"

**Comment by davidheerema** [comment]
@sastels @sdzhangtao I feel that we should be setting the content-type in the request header to the content moderator API correctly based on what we are passing it.  I think that may be why we are not getting the correct error message back for our situation.

Here is the API reference:
https://canadacentral.dev.cognitive.microsoft.com/docs/services/57cf753a3f9b070c105bd2c1/operations/57cf753a3f9b070868a1f66c

Here is some sample javascript code included at that reference:

```
<!DOCTYPE html>
<html>
<head>
    <title>JSSample</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
</head>
<body>

<script type="text/javascript">
    $(function() {
        var params = {
            // Request parameters
            "CacheImage": "{boolean}",
        };
      
        $.ajax({
            url: "https://canadacentral.api.cognitive.microsoft.com/contentmoderator/moderate/v1.0/ProcessImage/Evaluate?" + $.param(params),
            beforeSend: function(xhrObj){
                // Request headers
                xhrObj.setRequestHeader("Content-Type","application/json");
                xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key","{subscription key}");
            },
            type: "POST",
            // Request body
            data: "{body}",
        })
        .done(function(data) {
            alert("success");
        })
        .fail(function() {
            alert("error");
        });
    });
</script>
</body>
</html>
```

**Comment by sdzhangtao** [comment]
The content moderator we are using is just image moderator, as documented, it can only support image types. We will need to determine the file types before sending to Azure image moderator. If types not supported, don't send. Of course, we will set the right content-type header too.

**Comment by sdzhangtao** [comment]
Hi Dave,
I implemented a check to see whether the file type is supported or not. Can you try again?
Thanks

**Comment by davidheerema** [comment]
> Hi Dave,
> I implemented a check to see whether the file type is supported or not. Can you try again?

Test looks good, I see the console output when I do a pdf 👍 

Do you also want to implement the change to set the correct content type on the call to the moderator into this PR before we merge?  I don't exactly know how.  I think it has to do something with `_request`

**Comment by sdzhangtao** [comment]
It occurred to me that when we use the right file type, the content type will be set correctly.

**Comment by davidheerema** [comment]
> It occurred to me that when we use the right file type, the content type will be set correctly.

Did you test this and confirm it gets set correctly?

**Comment by sdzhangtao** [comment]
I tested it. I saw it, but I am not sure where. Will look into it again.

**Comment by sdzhangtao** [comment]
I read through the Azure image moderator javascript code, everything is hardcoded as image/gif.  The only time you can specify a content-type is when we do text moderator. I guess that's why we see image/gif when uploading a pdf.

**Pull request merged**
